### PR TITLE
fix: fix #179 Same watermark image is behaving differently on ANDROID and iOS

### LINKED ISSUE #179: Same watermark image is behaving differently on ANDROID and IOS when use given position enum
**Describe the bug**
When i am adding a watermark image on Android it is working perfectly as expected.
But when working on IOS the watermark image is losing its original aspect ratio and its getting very blurry.

**To Reproduce**
```
              Marker.markImage({
                    backgroundImage: {
                        src: IMAGEURL,
                        scale: 1,
                    },
                    watermarkImages: [{
                        src: wIMAGEURL,
                        position: {
                            position: Position.bottomLeft,
                        },
                        scale: 0.1,
                        // alpha: 1
                    }],
                    scale: 1,
                    quality: 100,
                }).then((path) => {
                    resolve(path)
                }).catch((error) => {
                    resolve(false)
                })
```

**Expected behavior**
IMAGE SHOULD BE SAME ON BOTH ANDROID AND IOS

I m using  CameraRoll library to download image afterwards
 CameraRoll.save(dPath, { type: 'photo', album: 'EducoreParent' }).then((res) => {
                        console.log('res', res);
                    }).catch((error) => {
                        console.log('error', error);
                    })

**Screenshots**
image

**Devlopment environment(please complete the following information):**
 - OS: MacOS 14.2 (23C64)
 - nodejs:  v18.18.0
 - react-native: 0.72.7
 - react-native-image-marker :  "^1.1.9"

**Smartphone (please complete the following information):**
 - Device: IOS 13ProMax  - OS: IOS 17.0
 -  - Device: Pixel 6  - OS: Android 13

### PR DESCRIPTION
**Pull request by JimmyDaddy**
fix #179

### CODE REVIEW

**Review by 163Gaddy — APPROVED** [review]

**Comment by EducoreAPK** [comment]
I updated to 1.2.0
Still the issue is with the aspect ratio of the watermark image.
it becomes squared in IOS and in android its perfectly of same aspect ratio as it should be. 
image
@JimmyDaddy

**Comment by JimmyDaddy** [comment]
@EducoreAPK Could you pls upload the icon so that I can test with it?

**Comment by EducoreAPK** [comment]
logo_center_2

**Comment by JimmyDaddy** [comment]
@EducoreAPK It seems that there is a large amount of white space on the right side of this image. You could try cropping the white space on the right side of the image first and see if that works. I will fix the issue of white pixel filtering on iOS later.

**Comment by EducoreAPK** [comment]
Actually its not white space there is text there in Black color

**Pull request merged**
